package enums

// Object type field
//
// Enumeration of object types
type ObjectType string

const (
	ObjectIssuer                                 ObjectType = "ISSUER"
	ObjectStakeholder                            ObjectType = "STAKEHOLDER"
	ObjectStockClass                             ObjectType = "STOCK_CLASS"
	ObjectStockLegendTemplate                    ObjectType = "STOCK_LEGEND_TEMPLATE"
	ObjectStockPlan                              ObjectType = "STOCK_PLAN"
	ObjectValuation                              ObjectType = "VALUATION"
	ObjectVestingTerms                           ObjectType = "VESTING_TERMS"
	ObjectTxConvertibleAcceptance                ObjectType = "TX_CONVERTIBLE_ACCEPTANCE"
	ObjectTxConvertibleCancellation              ObjectType = "TX_CONVERTIBLE_CANCELLATION"
	ObjectTxConvertibleConversion                ObjectType = "TX_CONVERTIBLE_CONVERSION"
	ObjectTxConvertibleIssuance                  ObjectType = "TX_CONVERTIBLE_ISSUANCE"
	ObjectTxConvertibleRetraction                ObjectType = "TX_CONVERTIBLE_RETRACTION"
	ObjectTxConvertibleTransfer                  ObjectType = "TX_CONVERTIBLE_TRANSFER"
	ObjectTxEquityCompensationAcceptance         ObjectType = "TX_EQUITY_COMPENSATION_ACCEPTANCE"
	ObjectTxEquityCompensationCancellation       ObjectType = "TX_EQUITY_COMPENSATION_CANCELLATION"
	ObjectTxEquityCompensationExercise           ObjectType = "TX_EQUITY_COMPENSATION_EXERCISE"
	ObjectTxEquityCompensationIssuance           ObjectType = "TX_EQUITY_COMPENSATION_ISSUANCE"
	ObjectTxEquityCompensationRelease            ObjectType = "TX_EQUITY_COMPENSATION_RELEASE"
	ObjectTxEquityCompensationRetraction         ObjectType = "TX_EQUITY_COMPENSATION_RETRACTION"
	ObjectTxEquityCompensationTransfer           ObjectType = "TX_EQUITY_COMPENSATION_TRANSFER"
	ObjectTxPlanSecurityAcceptance               ObjectType = "TX_PLAN_SECURITY_ACCEPTANCE"
	ObjectTxPlanSecurityCancellation             ObjectType = "TX_PLAN_SECURITY_CANCELLATION"
	ObjectTxPlanSecurityExercise                 ObjectType = "TX_PLAN_SECURITY_EXERCISE"
	ObjectTxPlanSecurityIssuance                 ObjectType = "TX_PLAN_SECURITY_ISSUANCE"
	ObjectTxPlanSecurityRelease                  ObjectType = "TX_PLAN_SECURITY_RELEASE"
	ObjectTxPlanSecurityRetraction               ObjectType = "TX_PLAN_SECURITY_RETRACTION"
	ObjectTxPlanSecurityTransfer                 ObjectType = "TX_PLAN_SECURITY_TRANSFER"
	ObjectTxStockAcceptance                      ObjectType = "TX_STOCK_ACCEPTANCE"
	ObjectTxStockCancellation                    ObjectType = "TX_STOCK_CANCELLATION"
	ObjectTxStockClassAuthorizedSharesAdjustment ObjectType = "TX_STOCK_CLASS_AUTHORIZED_SHARES_ADJUSTMENT"
	ObjectTxStockClassConversionRatioAdjustment  ObjectType = "TX_STOCK_CLASS_CONVERSION_RATIO_ADJUSTMENT"
	ObjectTxStockClassSplit                      ObjectType = "TX_STOCK_CLASS_SPLIT"
	ObjectTxStockConversion                      ObjectType = "TX_STOCK_CONVERSION"
	ObjectTxStockIssuance                        ObjectType = "TX_STOCK_ISSUANCE"
	ObjectTxStockPlanPoolAdjustment              ObjectType = "TX_STOCK_PLAN_POOL_ADJUSTMENT"
	ObjectTxStockPlanReturnToPool                ObjectType = "TX_STOCK_PLAN_RETURN_TO_POOL"
	ObjectTxStockReissuance                      ObjectType = "TX_STOCK_REISSUANCE"
	ObjectTxStockRepurchase                      ObjectType = "TX_STOCK_REPURCHASE"
	ObjectTxStockRetraction                      ObjectType = "TX_STOCK_RETRACTION"
	ObjectTxStockTransfer                        ObjectType = "TX_STOCK_TRANSFER"
	ObjectTxVestingAcceleration                  ObjectType = "TX_VESTING_ACCELERATION"
	ObjectTxVestingEvent                         ObjectType = "TX_VESTING_EVENT"
	ObjectTxVestingStart                         ObjectType = "TX_VESTING_START"
	ObjectTxWarrantAcceptance                    ObjectType = "TX_WARRANT_ACCEPTANCE"
	ObjectTxWarrantCancellation                  ObjectType = "TX_WARRANT_CANCELLATION"
	ObjectTxWarrantExercise                      ObjectType = "TX_WARRANT_EXERCISE"
	ObjectTxWarrantIssuance                      ObjectType = "TX_WARRANT_ISSUANCE"
	ObjectTxWarrantRetraction                    ObjectType = "TX_WARRANT_RETRACTION"
	ObjectTxWarrantTransfer                      ObjectType = "TX_WARRANT_TRANSFER"
)
